from string import ascii_uppercase
from math import log
#longitud 5, clave de 5 letras
alfa = ascii_uppercase

cadena = "WUBEFIQLZURMVOFEHMYMWTIXCGTMPIFKRZUPMVOIRQMMWOZMPULMBNYVQQQMVMVJLEYMHFEFNZPSDLPPSDLPEVQMWCXYMDAVQEEFIQCAYTQOWCXYMWMSEMEFCFWYEYQETRLIQYCGMTWCWFBSMYFPLRXTQYEEXMRULUKSGWFPTLRQAERLUVPMVYQYCXTWFQLMTELSFJPQEHMOZCIWCIWFPZSLMAEZIQVLQMZVPPXAWCSMZMORVGVVQSZETRLQZPBJAZVQIYXEWWOICCGDWHQMMVOWSGNTJPFPPAYBIYBJUTWRLQKLLLMDPYVACDCFQNZPIFPPKSDVPTIDGXMQQVEBMQALKEZMGCVKUZKIZBZLIUAMMVZ"

"""length = len(cadena)

prob = list()

for letra in alfa:
    
    prob.append(cadena.count(letra)/length)
    
entropia = 0
    
for porcentaje in prob:
    
    entropia = entropia + (porcentaje * log(1/porcentaje))
    
print(entropia)"""


